### ISSUE TITLE
Some dead links on Table of Contents in README

### ISSUE THREAD

**Issue by piratejas** [methods/govuk-a11y-project#7]
Probably typos somewhere.

(This is not a serious issue by the way - we are just trying out how to raise issues on Github)

**Comment by nshumoogum** [comment]
Previous solution to use an alias as anchor using html was replaced by using markdown reference links, however the tool that was used to generate the link reference to the header understands emojis while urls do not. Hence the markdown reference links in the "Table of Contents" need updating, see [feature/test-markdown branch](https://github.com/methods/govuk-a11y-project/tree/feature/test-markdown#-table-of-contents) and [comparison to dev branch](https://github.com/methods/govuk-a11y-project/compare/dev...feature/test-markdown?expand=1)
